source: /src/
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
paths:
  static: ''
  uploads: uploads
timezone: Europe/London
markdown:
  engine: commonmark
  options:
    html: true
